# APP
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: kube-example
  name: web-app
spec:
  selector:
    matchLabels:
      app: web-app
  replicas: 2
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - image: alexwhen/docker-2048
        imagePullPolicy: Always
        name: web-app-container
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: kube-example
  name: web-app-np
spec:
  type: NodePort
  ports:
    - port: 443
      targetPort: 80
      protocol: TCP
  selector:
    app: web-app